# Project: Perpustakaan
# Makefile created by Dev-C++ 5.7.1

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = lib.o main.o murid.o buku.o peminjaman.o t_murid.o
LINKOBJ  = lib.o main.o murid.o buku.o peminjaman.o t_murid.o
LIBS     = -L"C:/Users/Student2014/Desktop/Dev-Cpp/MinGW64/lib" -L"C:/Users/Student2014/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Users/Student2014/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/Student2014/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Student2014/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"C:/Users/Student2014/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/Student2014/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Student2014/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"C:/Users/Student2014/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = Perpustakaan.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

lib.o: lib.cpp
	$(CPP) -c lib.cpp -o lib.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

murid.o: murid.cpp
	$(CPP) -c murid.cpp -o murid.o $(CXXFLAGS)

buku.o: buku.cpp
	$(CPP) -c buku.cpp -o buku.o $(CXXFLAGS)

peminjaman.o: peminjaman.cpp
	$(CPP) -c peminjaman.cpp -o peminjaman.o $(CXXFLAGS)

t_murid.o: t_murid.cpp
	$(CPP) -c t_murid.cpp -o t_murid.o $(CXXFLAGS)
